
<h1 class="page-header"><?= ucwords("$model"), ": <span>$action_name</span>" ?></h1>
<div class="row">
    <div class="col-lg-12">


        <div class="panel panel-primary">
            <div class="panel-heading">
                <?= ucwords("$model"), ": <span>$action_name</span>" ?>
            </div>
            <div class="panel-body">
                <?php ModelForm::create($$model) ?>
            </div>
            <div class="panel-footer">
                <a href="../" class="btn btn-warning btn-sm">Volver</a>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(":text, :password").addClass("form-control");
    $("select").addClass("form-control");
    $("textarea").addClass("form-control");
    $(':input[type="number"]').addClass("form-control");
    $(':input[type="date"]').addClass("form-control");

    $(':submit').addClass("btn btn-success");
    $(".flash").addClass("alert alert-sm alert-warning");
</script>
