<div class='row'>
    <div class="col-12">
        <h2><?= ucwords("$model"), ": <span>$action_name</span>" ?></h2>


    </div>

    <div class='row'>
        <div class="col-1"></div>
        <div class="col-11 pull-right">
            <?= Html::linkAction("crear/", 'Crear registro', 'class="btn btn-primary"') ?>
        </div>
    </div>
    <div class='row'>
        <div class="col-12">&nbsp;</div>

    </div>

    <?php if ($data->items) : ?>
        <div class='row'>
            <div class='col-12'>

                <table class="table table-bordered table-responsive">
                    <thead><tr>
                            <?php foreach (current($data->items)->fields as $field) : ?>
                                <th><?= (current($data->items)->get_alias($field)) ?></th>
                            <?php endforeach ?>
                            <th>Acciones</th>
                        </tr></thead>
                    <tbody>
                        <?php foreach ($data->items as $item) : ?>
                            <tr>
                                <?php foreach ($item->fields as $field) : ?>
                                    <td><?= h($item->$field) ?></td>
                                <?php endforeach ?>
                                <td><?= Html::linkAction("ver/$item->id", 'Ver') ?> |
                                    <?= Html::linkAction("editar/$item->id", 'Editar') ?> |
                                    <?= Html::linkAction("borrar/$item->id", 'Borrar', 'onclick="return confirm(\'¿Está seguro?\')"') ?>
                                </td>
                            </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>

            </div>
        </div>
        <div class="row">
            <div class="col-12 pull-right">

                <?php View::partial('paginators/digg', false, array('page' => $data, 'url' => Router::get('controller_path') . '/index')); ?>

            </div>
        </div>

    <?php else : // Si no hay items?>
        <h2>No hay ningún registro</h2>
    <?php endif ?>

