<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
        <?php Tag::css('bootstrap.min') ?>
        <?php Tag::css('font-awesome.min') ?>
        <?php Tag::css('metisMenu.min') ?>
        <?php Tag::css('morris') ?>
        <?php Tag::css('pickadate') ?>
        <?php Tag::css('sb-admin-2') ?>
        <?php Tag::css('timeline') ?>
        <?= Html::includeCss() ?>
    </head>
    <body>
        <div class="container">
            <?php View::content() ?>
        </div>

        <?= Tag::js("jquery.min"); ?>
        <?= Tag::js("bootstrap.min"); ?>
        <?= Tag::js("html5shiv"); ?>
        <?= Tag::js("metisMenu.min"); ?>
        <?= Tag::js("morris-data"); ?>
        <?= Tag::js("morris.min"); ?>
        <?= Tag::js("raphael-min"); ?>
        <?= Tag::js("sb-admin-2"); ?>
    </body>
</html>
